### ISSUE TITLE
[bug] There isn't `popen` in MSVC.

### ISSUE THREAD

**Issue by hwhsu1231** [gammasoft71/Examples_FLTK#1]
There isn't `popen` in MSVC. Therefore it will cause an error.

```
error C3861: 'popen': identifier not found
```

https://github.com/gammasoft71/Examples_FLTK/blob/master/src/Hello_Worlds/Hello_World_Say/Hello_World_Say.cpp#L26

Instead, it has [`_popen`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-170). So I added the following codes before calling `popen`, and it worked.

```c++
#ifdef _WIN32
#   define popen _popen
#endif
```

**Comment by gammasoft71** [comment]
Thank you for your contribution. I did fix it
