### ISSUE TITLE
Is there some ftlk-theme for fltk for widgts or buttons ? 

### ISSUE THREAD

**Issue by xx-zhang** [gammasoft71/Examples_FLTK#2]
Is there some ftlk-theme for fltk for widgts or buttons ? 
as i see, rust fltk have some theme

https://github.com/fltk-rs/fltk-theme

**Comment by gammasoft71** [comment]
Hi,

Not to my knowledge, I had already seen that fltk rust had themes. But I haven't found anything equivalent in c++.
It would be interesting to look at fltk rust themes and see if it would be possible to take the concept and port it to C++. 
This could be a great project on Github. 

For information, in this project, which is only intended to show how to use fltk with modern C++, I have an example [Scheme_Modes](https://github.com/gammasoft71/Examples_FLTK/blob/master/src/User_Components/Scheme_Modes/README.md) which allows you to vary the colors of predefined fltk schemes. 
But not to modify schemes.

Have a good day

Gammasoft71

**Comment by xx-zhang** [comment]
Have a good day, thank you @gammasoft71
